// Code generated by goctl. DO NOT EDIT!
// Source: order.proto

package ordersvc

import (
	"context"

	"github.com/kevwan/gozero-dtm/order/pb"

	"github.com/tal-tech/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Response     = pb.Response
	TransferInfo = pb.TransferInfo

	OrderSvc interface {
		Transfer(ctx context.Context, in *TransferInfo, opts ...grpc.CallOption) (*Response, error)
	}

	defaultOrderSvc struct {
		cli zrpc.Client
	}
)

func NewOrderSvc(cli zrpc.Client) OrderSvc {
	return &defaultOrderSvc{
		cli: cli,
	}
}

func (m *defaultOrderSvc) Transfer(ctx context.Context, in *TransferInfo, opts ...grpc.CallOption) (*Response, error) {
	client := pb.NewOrderSvcClient(m.cli.Conn())
	return client.Transfer(ctx, in, opts...)
}
